namespace = "Sample"
local_include = ["serializer.hpp"]
include = ["cstdint","vector","string","array","nlohmann/json.hpp","memory"]
struct_name = "Test"

serializer_json = "nlohmann::json"
serializer = "Serializer"
binary_version = 100
lua = true

compare = true
copy = true

[[member]]
name = "index"
type = "bit-unsigned"
bits = 5
initial = 10
[[member]]
name = "beer_type"
type = "bit-enum"
cast = "BeerType"
bits = 5
enum = ["Ales","Larger","Pilsner","Lambic","IPA"]
initial = "IPA"
[[member]]
name = "generation"
type = "bit-signed"
bits = 3
initial = 0
[[member]]
name = "enabled"
type = "bit-bool"
initial = false
[[member]]
name = "count"
type = "int"
initial = 0
[[member]]
name = "max_speed"
type = "uint32_t"
initial = 320
[[member]]
name = "ranking"
type = "uint8_t"
container = "std::vector"
reserve = 32
[[member]]
name = "line"
type = "float"
container = "std::vector"
reserve = 8
[[member]]
name = "note"
type = "Note"
container = "std::array"
reserve = 4
    [[member.Note]]
    name = "page"
    type = "int"
    initial = 0
    [[member.Note]]
    name = "line"
    type = "int"
    initial = 0
[[member]]
name = "child"
type = "Child"
    [[member.Child]]
    name = "name"
    type = "std::string"
    initial = "father"
    [[member.Child]]
    name = "age"
    type = "bit-unsigned"
    bits = 6
    offset = 18
    initial = 50
    [[member.Child]]
    name = "step"
    type = "bit-unsigned"
    bits = 4
    scale = 5
    initial = 20
[[member]]
name = "entry_list"
type = "Entry"
container = "std::vector"
    [[member.Entry]]
    name = "name"
    type = "std::string"
    [[member.Entry]]
    name = "country"
    type = "std::string"
    [[member.Entry]]
    name = "point"
    type = "uint16_t"
    [[member.Entry]]
    name = "wins"
    type = "uint8_t"
